logging:
  level:
    de.herhold.spielwiese: DEBUG
    root: INFO
#spring:
  #datasource:
  #  url: r2dbc:h2:mem:mydb;MODE=PostgreSQL
  #  driver-class-name: org.h2.Driver
  #  username: sa
 #  password: pw
